goal_0:
  pose:
    position:
      x: 1.0
      y: -2.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.57

goal_1:
  pose:
    position:
      x: -6.5
      y: -6.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.57

goal_2:
  pose:
    position:
      x: -6.0
      y: -2.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 3.14

goal_3:
  pose:
    position:
      x: 3.0
      y: 4.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0

goal_4:
  pose:
    position:
      x: 6.0
      y: -4.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
